language: c
# Blacklist
branches:
  except:
    - gh-pages
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/Neo
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/Hello/Hello.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Invader/Invader.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Signs/Signs.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/SignsScroll/SignsScroll.ino
  - arduino --verify --board esp8266:esp8266:nodemcuv2 $PWD/examples/MatrixEditor/MatrixEditor.ino
notifications:
  email:
    on_success: change
    on_failure: change